oc_plateform_home:
    path: /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:        1
    requirements:
     page: \d*

oc_plateform_view:
    path: /advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+

oc_plateform_add:
    path: /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

oc_plateform_edit:
    path: /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_plateform_delete:
    path: /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+
